mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panoramas/', include('panoramas.urls')),
    path('mapPoints/', include('mapPoints.urls')),
    path('ocr/', include('ocr.urls')),
    path('signs/', include('signs.urls')),
    path('viewer/', include('viewer.urls')),
]

ocr/urls.py
from django.urls import path

from . import views

app_name = 'ocr'
urlpatterns = [
    path('overview/', views.overview, name='overview'),
    path('create_Ocr/', views.create_Ocr, name='create_Ocr'),
    path('detail/<int:ocr_pk>/', views.detail, name='detail'),
    path('worker_get_ocr/<int:worker_id>/', views.worker_get_ocr, name='worker_get_ocr'),
    path('overlay/<int:ocr_pk>/<int:x1>/<int:x2>/<int:y1>/<int:y2>/', views.overlay, name='overlay'),
]

panoramas/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'panoramas'
urlpatterns = [
    path('create_Panorama/', views.create_Panorama, name='create_Panorama'),

    path('overview/', views.overview, name='overview'),
    path('detailNeighborhood/<int:neighborhood_pk>/', views.detailNeighborhood, name='detailNeighborhood'),
    path('googleViewer/<int:panorama_pk>/', views.googleViewer, name='googleViewer'),
    path('detail/<int:panorama_pk>/', views.detail, name='detail'),
    path('worker_get_panorama/<int:worker_id>/', views.worker_get_panorama, name='worker_get_panorama'),
    ]

ocr/models.py
from django.db import models
from panoramas.models import Panorama
from mysite.settings import *
import ast




class Ocr(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    panorama = models.ForeignKey(Panorama, on_delete=models.CASCADE)
    pano_image_name = models.TextField(blank=True)
    depth_image_name = models.TextField(blank=True)
    google_ocr_json = models.TextField(blank=True)
    google_ocr_run = models.BooleanField(default=False)
    width_pano = models.IntegerField()  # this is the height of the subimage, NOT the entire depth image
    height_pano = models.IntegerField() # this is the height of the subimage, NOT the entire panorama image
    width_depth = models.IntegerField()
    height_depth = models.IntegerField()
    direction = models.FloatField() # This is the heading of the subimage, NOT the car. You have to add to get the true heading. Normalized [0,1]
                                    # 0.25 = left = -90, 0.75 = right = +90,
                                    # 0, -180    0.25,-90    0.5,0    0.75,90,   1,180
                                    #  y =  360*x - 180
    fov_x = models.FloatField() # this is the fov of the subimage, NOT the ocr sign
    fov_y = models.FloatField()
    lock_ocr = models.BooleanField(default=False)

    def __str__(self):
        return str(self.panorama)

    def url_pano_image(self):
        url = AWS_BASE_URL + self.pano_image_name
        return url        

    def url_depth_image(self):
        url = AWS_BASE_URL + self.depth_image_name
        return url        

    def run_google_ocr(self):
        self.google_ocr_run = True
        self.save()

    def json(self):
        """
        Returns json
        TODO: horribly unsafe
        """
        if self.google_ocr_json:
            return ast.literal_eval(self.google_ocr_json)
        else:
            return None

class QueueOcr(models.Model):
    ocr = models.ForeignKey(Ocr, on_delete=models.CASCADE)

    @staticmethod
    def ocr_list(n=10):
        try:            
            queue = QueueOcr.objects.all()[0:n]
        except:
            count = QueueOcr.objects.count()
            queue = QueueOcr.objects.all()[0:count]
        
        ocr_pks = queue.values_list('ocr', flat=True)
        ocr_queryset = Ocr.objects.filter(pk__in=ocr_pks)

        QueueOcr.objects.filter(pk__in=list( queue.values_list('pk', flat=True)  )).delete()
        return ocr_queryset

panoramas/models.py
from django.db import models
from mapPoints.models import MapPoint
from mysite.settings import *
from django.forms.models import model_to_dict

class Panorama(models.Model):
    # used for parallel processing
    lock = models.BooleanField(default=False)
    #signs_written = models.BooleanField(null=True) # this is used to determine whether signs have already been written to text file. The reason why we don't do this in the Ocr object is because filter is very slow

    # associated mapPoint
    mapPoint = models.ForeignKey(MapPoint, on_delete=models.CASCADE)

    # date that this object was created
    created_date = models.DateTimeField(auto_now_add=True)

    # date that car acquired panorama
    year = models.IntegerField()
    month = models.IntegerField()

    # metadata for panorama image
    pano_image_width = models.FloatField()
    pano_image_height = models.FloatField()
    pano_image_name = models.TextField(blank=True)

    # metadata for depth image
    depth_image_width = models.FloatField()
    depth_image_height = models.FloatField()
    depth_image_name = models.TextField(blank=True)

    # miscellaneous
    heading = models.FloatField()
    lon = models.FloatField()
    lat = models.FloatField()
    panoid = models.TextField(blank=True)
    address = models.TextField(blank=True)
    num_links = models.IntegerField()


    def __str__(self):
        return self.pano_image_name

    def url_pano_image(self):
        url = AWS_BASE_URL + self.pano_image_name
        return url

    def url_depth_image(self):
        url = AWS_BASE_URL + self.depth_image_name
        return url

    def info_all(self):
        p = Panorama.objects.filter(pk=self.pk)[0]
        return model_to_dict(p)


class NeighboringPanoramas(models.Model):
    mapPoint = models.ForeignKey(MapPoint, on_delete=models.CASCADE)
    panoramas = models.ManyToManyField(Panorama,related_name='panoramas')
    centerPanorama = models.ForeignKey(Panorama, on_delete=models.CASCADE)

panoramas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import transaction
import time
import os.path
import random
import json
from django.views.decorators.csrf import csrf_exempt
from .models import *
from mapPoints.models import MapPoint
import ast
import datetime

# Worker uses this view to get Panorama data for ocr processing
def worker_get_panorama(request, worker_id):

    # A clumsy way to solve concurrency conditions
    while(os.path.isfile('.lock')):
        print('database locked')
        time.sleep(random.uniform(0.1, 0.5))
    f = open(".lock","w")
    f.close()

    # check if we are done with all panoramas
    count = Panorama.objects.filter(lock=False,year__gte=0).count()
    if count == 0:
        os.remove(".lock") 
        return HttpResponse("done")

    # Get a Panorama to pass to worker
    #p = Panorama.objects.filter(lock=False).first()
    # Filter by year, 

    while(1):
        p = Panorama.objects.filter(lock=False,year__gte=0).first()
        if p.ocr_set.all().count() > 0: # ocr was previously run
            print("ocr previously run on panorama.pk=",p.pk)
            p.lock =  True
            p.save()
        else: # ocr was not run previously
            break            

    # lock panorama
    p.lock =  True
    p.save()
    # log worker communication
    out_str = "sent panorama pk=" + str(p.pk) + " to worker_id=" + str(worker_id) + " at " + str(datetime.datetime.now()) + "\n"
    with open(BASE_DIR + "worker_log.txt", "a") as myfile:
        myfile.write(out_str)

    # Remove lock against concurrency
    os.remove(".lock") 

    # Send MapPoint data to worker
    data = {'panorama_pk' : p.pk,
            'pano_image_name' : p.pano_image_name,
            'depth_image_name'  : p.depth_image_name,
            'panoid': p.panoid,}

    # _ = Panorama.objects.filter(lock=False,year__gte=2010)
    # print(_.count())
    # print(p.pk)
    #             
    return HttpResponse(json.dumps(data), content_type = "application/json")




# panorama/controls.py: worker_create_panoramas uses this interface to communicate data back to master
# TODO: not secure
@csrf_exempt
def create_Panorama(request):


    post = request.POST
    json_str = post.get('json_str')
    d = ast.literal_eval(json_str)

    for i,pano_metadata in enumerate(d):
        p = Panorama(mapPoint = MapPoint.objects.get(pk=pano_metadata['mapPoint_pk']),
                    year = pano_metadata['year'],
                    month = pano_metadata['month'],
                    pano_image_width = pano_metadata['pano_image_width'],
                    pano_image_height = pano_metadata['pano_image_height'],
                    depth_image_width = pano_metadata['depth_width'],
                    depth_image_height = pano_metadata['depth_height'],
                    heading = pano_metadata['heading'],
                    lon = pano_metadata['lon'],
                    lat = pano_metadata['lat'],
                    panoid = pano_metadata['panoid'],
                    address = pano_metadata['address'],
                    num_links = pano_metadata['num_links'],
                    pano_image_name = pano_metadata['pano_image_name'],
                    depth_image_name = pano_metadata['depth_image_name'],)
        p.save()
        print(p)

        if i == 0:
            neighboringPanoramas = NeighboringPanoramas(mapPoint = MapPoint.objects.get(pk=pano_metadata['mapPoint_pk']),
                                                        centerPanorama = p,)
            neighboringPanoramas.save()
        neighboringPanoramas.panoramas.add(p)
    neighboringPanoramas.save()
    return HttpResponse('Panorama objects created')

def overview(request):
    num_panoramas = Panorama.objects.count()
    return HttpResponse(num_panoramas)

def detail(request,panorama_pk):
    p = Panorama.objects.get(pk=panorama_pk)
    context = {'panorama' : p}
    return render(request, 'panoramas/detail.html',context)
def googleViewer(request,panorama_pk):
    p = Panorama.objects.get(pk=panorama_pk)
    context = {'panorama' : p}
    return render(request, 'panoramas/googleViewer.html',context)

def detailNeighborhood(request,neighborhood_pk):
    neighborhood = NeighboringPanoramas.objects.get(pk=neighborhood_pk)
    context = {'neighborhood' : neighborhood}
    return render(request, 'panoramas/detailNeighborhood.html',context)

# Worker uses this view to get a MapPoint for panorama scraping
def test(request):
    """
    docstring
    """
    while(os.path.isfile('.lock')):
        print('database locked')
        time.sleep(random.uniform(0, 1))
    lock_file = open(".lock","w")
    lock_file.close()

    # Get a MapPoint to pass to worker
    mapPoint = MapPoint.objects.filter(lock=False).first()
    mapPoint.lock=True
    mapPoint.save()

    os.remove(".lock") 
    return HttpResponse(mapPoint)

panoramas/templates/panoramas/detail.html
{% block javascript %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<script>
/**
 * Sets all our panos to point in a particular direction.
 */

var MCPanoID = "{{panorama.panoid}}";
var MCHeading = 0 //"{{panorama.heading}}"
function initializeAllPanos() {
  panoId = MCPanoID
  setStreetViewPanorama('panoBig', panoId, MCHeading, 0);
}
 
/**
 * Sets up the given div as a StreetView Panorama, with the given view angles.
 * @param {string} panoId The panorama id. Eg: 'RJd2HuqmShMAAAQfCa3ulg'.
 * @param {number} headingAngle The degree angle offset from North (clockwise?).
 * @param {number} pitchAngle The degree angle upset up/down.
 */
function setStreetViewPanorama(divId, panoId, headingAngle, pitchAngle) {
  var panoramaOptions = {
    // pano: panoId,  // Wanted to demonstrate 'setPano' instead.
    pov: {
      heading: headingAngle,
      pitch: pitchAngle,
      zoom: 1
    }
  };
  var panorama = new google.maps.StreetViewPanorama(document.getElementById(divId), panoramaOptions);
  panorama.setPano(panoId);
}
 
google.maps.event.addDomListener(window, 'load', initializeAllPanos);
</script>

{% endblock %}

{% block body_block %}


<a href="{{ panorama.url_pano_image }}">panorama image</a>
<br />
<a href="{{ panorama.url_depth_image }}">depth image</a>
<br />
<a href="{% url 'ocr:detail' panorama.ocr_set.all.0.pk %}">ocr image</a>
<br />


date google car = {{ panorama.month }}-{{ panorama.year }}
<br />

heading = {{ panorama.heading }}
<br />

(lon,lat) = ( {{ panorama.lon }},{{panorama.lat}})

<br />
panorama id = {{ panorama.panoid }}
<br />

address = {{ panorama.address }}
<br />

num_links = {{ panorama.num_links }}
<br />
MapPoint pk = {{ panorama.mapPoint.pk }}
<br />

<div id="panoBig" style="width: 600px; height: 300px;"></div>

{% endblock %}

panoramas/templates/panoramas/detailNeighborhood.html
{% block javascript %}

{% endblock %}

{% block body_block %}

neighborhood_pk = {{ neighborhood.pk }}

<h1>Neighboring panoramas</h1>
{% for p in neighborhood.panoramas.all %}
  <a href="{% url 'panoramas:detail' p.pk %}">panorama pk={{p.pk}}</a>
  <br />
{% endfor %}

<h1>Center panorama</h1>
center is panorama pk={{neighborhood.centerPanorama.pk}}

{% endblock %}

panoramas/templates/panoramas/googleViewer.html
{% block javascript %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<script>
/**
 * Sets all our panos to point in a particular direction.
 */

var MCPanoID = "{{panorama.panoid}}";
var MCHeading = 0 //"{{panorama.heading}}"
function initializeAllPanos() {
  panoId = MCPanoID
  setStreetViewPanorama('panoBig', panoId, MCHeading, 0);
}
 
/**
 * Sets up the given div as a StreetView Panorama, with the given view angles.
 * @param {string} panoId The panorama id. Eg: 'RJd2HuqmShMAAAQfCa3ulg'.
 * @param {number} headingAngle The degree angle offset from North (clockwise?).
 * @param {number} pitchAngle The degree angle upset up/down.
 */
function setStreetViewPanorama(divId, panoId, headingAngle, pitchAngle) {
  var panoramaOptions = {
    // pano: panoId,  // Wanted to demonstrate 'setPano' instead.
    pov: {
      heading: headingAngle,
      pitch: pitchAngle,
      zoom: 1
    }
  };
  var panorama = new google.maps.StreetViewPanorama(document.getElementById(divId), panoramaOptions);
  panorama.setPano(panoId);
}
 
google.maps.event.addDomListener(window, 'load', initializeAllPanos);
</script>

{% endblock %}

{% block body_block %}
<div id="panoBig" style="width: 600px; height: 300px;"></div>
{% endblock %}