mapPoints/urls.py
from django.urls import path

from . import views

app_name = 'mapPoints'
urlpatterns = [
    path('overview/', views.overview, name='overview'),
    path('worker_get_mapPoint/<int:worker_id>/', views.worker_get_mapPoint, name='worker_get_mapPoint'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panoramas/', include('panoramas.urls')),
    path('mapPoints/', include('mapPoints.urls')),
    path('ocr/', include('ocr.urls')),
    path('signs/', include('signs.urls')),
    path('viewer/', include('viewer.urls')),
]

ocr/urls.py
from django.urls import path

from . import views

app_name = 'ocr'
urlpatterns = [
    path('overview/', views.overview, name='overview'),
    path('create_Ocr/', views.create_Ocr, name='create_Ocr'),
    path('detail/<int:ocr_pk>/', views.detail, name='detail'),
    path('worker_get_ocr/<int:worker_id>/', views.worker_get_ocr, name='worker_get_ocr'),
    path('overlay/<int:ocr_pk>/<int:x1>/<int:x2>/<int:y1>/<int:y2>/', views.overlay, name='overlay'),
]

panoramas/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'panoramas'
urlpatterns = [
    path('create_Panorama/', views.create_Panorama, name='create_Panorama'),

    path('overview/', views.overview, name='overview'),
    path('detailNeighborhood/<int:neighborhood_pk>/', views.detailNeighborhood, name='detailNeighborhood'),
    path('googleViewer/<int:panorama_pk>/', views.googleViewer, name='googleViewer'),
    path('detail/<int:panorama_pk>/', views.detail, name='detail'),
    path('worker_get_panorama/<int:worker_id>/', views.worker_get_panorama, name='worker_get_panorama'),
    ]

signs/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'signs'
urlpatterns = [    
    path('detail/<int:sign_pk>/', views.detail, name='detail'),
    ]

viewer/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'viewer'
urlpatterns = [
    path('mapPoint/<int:pk>/', views.mapPoint, name='mapPoint'),
    path('objectID/<int:object_id>/', views.objectID, name='objectID'),
    path('panorama/<int:pk>/', views.panorama, name='panorama'),
    path('ocr/<int:pk>/', views.ocr, name='ocr'),
    path('overlaySigns/<int:ocr_pk>/', views.overlaySigns, name='overlaySigns'),
    path('overlaySignsFOV/<int:ocr_pk>/<int:fov>', views.overlaySignsFOV, name='overlaySignsFOV'),
    path('ain/<int:ain>/', views.ain, name='ain'),
    ]

mapPoints/models.py
from django.db import models


class MapPoint(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    object_id = models.IntegerField() # julia's index in shapefile
    lon = models.FloatField()
    lat = models.FloatField()
    lock = models.BooleanField(default=False)
    shapefile_name = models.TextField(blank=True)
    year1 = models.IntegerField(default=2017)
    year2 = models.IntegerField(default=2018)
    def __str__(self):
        return 'pk= '+ str(self.pk) +'   ,   (lon,lat) = ' + str(self.lon) + ", "+str(self.lat)
        

ocr/models.py
from django.db import models
from panoramas.models import Panorama
from mysite.settings import *
import ast




class Ocr(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    panorama = models.ForeignKey(Panorama, on_delete=models.CASCADE)
    pano_image_name = models.TextField(blank=True)
    depth_image_name = models.TextField(blank=True)
    google_ocr_json = models.TextField(blank=True)
    google_ocr_run = models.BooleanField(default=False)
    width_pano = models.IntegerField()  # this is the height of the subimage, NOT the entire depth image
    height_pano = models.IntegerField() # this is the height of the subimage, NOT the entire panorama image
    width_depth = models.IntegerField()
    height_depth = models.IntegerField()
    direction = models.FloatField() # This is the heading of the subimage, NOT the car. You have to add to get the true heading. Normalized [0,1]
                                    # 0.25 = left = -90, 0.75 = right = +90,
                                    # 0, -180    0.25,-90    0.5,0    0.75,90,   1,180
                                    #  y =  360*x - 180
    fov_x = models.FloatField() # this is the fov of the subimage, NOT the ocr sign
    fov_y = models.FloatField()
    lock_ocr = models.BooleanField(default=False)

    def __str__(self):
        return str(self.panorama)

    def url_pano_image(self):
        url = AWS_BASE_URL + self.pano_image_name
        return url        

    def url_depth_image(self):
        url = AWS_BASE_URL + self.depth_image_name
        return url        

    def run_google_ocr(self):
        self.google_ocr_run = True
        self.save()

    def json(self):
        """
        Returns json
        TODO: horribly unsafe
        """
        if self.google_ocr_json:
            return ast.literal_eval(self.google_ocr_json)
        else:
            return None

class QueueOcr(models.Model):
    ocr = models.ForeignKey(Ocr, on_delete=models.CASCADE)

    @staticmethod
    def ocr_list(n=10):
        try:            
            queue = QueueOcr.objects.all()[0:n]
        except:
            count = QueueOcr.objects.count()
            queue = QueueOcr.objects.all()[0:count]
        
        ocr_pks = queue.values_list('ocr', flat=True)
        ocr_queryset = Ocr.objects.filter(pk__in=ocr_pks)

        QueueOcr.objects.filter(pk__in=list( queue.values_list('pk', flat=True)  )).delete()
        return ocr_queryset

panoramas/models.py
from django.db import models
from mapPoints.models import MapPoint
from mysite.settings import *
from django.forms.models import model_to_dict

class Panorama(models.Model):
    # used for parallel processing
    lock = models.BooleanField(default=False)
    #signs_written = models.BooleanField(null=True) # this is used to determine whether signs have already been written to text file. The reason why we don't do this in the Ocr object is because filter is very slow

    # associated mapPoint
    mapPoint = models.ForeignKey(MapPoint, on_delete=models.CASCADE)

    # date that this object was created
    created_date = models.DateTimeField(auto_now_add=True)

    # date that car acquired panorama
    year = models.IntegerField()
    month = models.IntegerField()

    # metadata for panorama image
    pano_image_width = models.FloatField()
    pano_image_height = models.FloatField()
    pano_image_name = models.TextField(blank=True)

    # metadata for depth image
    depth_image_width = models.FloatField()
    depth_image_height = models.FloatField()
    depth_image_name = models.TextField(blank=True)

    # miscellaneous
    heading = models.FloatField()
    lon = models.FloatField()
    lat = models.FloatField()
    panoid = models.TextField(blank=True)
    address = models.TextField(blank=True)
    num_links = models.IntegerField()


    def __str__(self):
        return self.pano_image_name

    def url_pano_image(self):
        url = AWS_BASE_URL + self.pano_image_name
        return url

    def url_depth_image(self):
        url = AWS_BASE_URL + self.depth_image_name
        return url

    def info_all(self):
        p = Panorama.objects.filter(pk=self.pk)[0]
        return model_to_dict(p)


class NeighboringPanoramas(models.Model):
    mapPoint = models.ForeignKey(MapPoint, on_delete=models.CASCADE)
    panoramas = models.ManyToManyField(Panorama,related_name='panoramas')
    centerPanorama = models.ForeignKey(Panorama, on_delete=models.CASCADE)

signs/models.py
from django.db import models
from mysite.settings import *
from ocr.models import Ocr

class Sign(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    ocr = models.ForeignKey(Ocr, on_delete=models.CASCADE)
    x1 = models.IntegerField()
    x2 = models.IntegerField()
    y1 = models.IntegerField()
    y2 = models.IntegerField()
    text = models.TextField(blank=True)
    languages = models.TextField(blank=True)
    distance = models.FloatField(blank=True,null=True)
    lat_sign = models.FloatField(blank=True,null=True)
    lon_sign = models.FloatField(blank=True,null=True)
    confidence = models.FloatField(blank=True,null=True)
    ain = models.IntegerField(blank=True,null=True)
    
    def __str__(self):
        return str(self.y1)
    def width(self):
        return self.x2-self.x1
    def height(self):
        return self.y2-self.y1

    def x_fraction(self):
        return (float(self.x2) + float(self.x1))/2 / float(self.ocr.width_pano)

    def absolute_heading(self):
        """
        calculates the absolute heading of the sign (i.e., car + camera)
        """
        heading_car_degrees = self.ocr.panorama.heading
        heading_camera_degrees = 360 * self.ocr.direction - 180


        x_fraction_subimage = self.x_fraction()  # (float(self.x2) + float(self.x1))/2 / float(self.ocr.width_pano)
        # 0.5 -> 0
        # 0   -> -fov/2
        # 1   -> +fov/2
        # y =  fov*x - fov/2
        # fov is the % of dimx, i.e., 20 means 20% of dimx
        heading_sign_degrees = (self.ocr.fov_x*x_fraction_subimage  -  self.ocr.fov_x / 2)/100 * 360

        absolute_heading = heading_car_degrees + heading_camera_degrees + heading_sign_degrees
        return absolute_heading

    def absolute_heading_new(self,panorama):
        """
        calculates the absolute heading of the sign (i.e., car + camera)
        """
        heading_car_degrees = panorama.heading
        heading_camera_degrees = 360 * self.ocr.direction - 180


        x_fraction_subimage = self.x_fraction()  # (float(self.x2) + float(self.x1))/2 / float(self.ocr.width_pano)
        # 0.5 -> 0
        # 0   -> -fov/2
        # 1   -> +fov/2
        # y =  fov*x - fov/2
        # fov is the % of dimx, i.e., 20 means 20% of dimx
        heading_sign_degrees = (self.ocr.fov_x*x_fraction_subimage  -  self.ocr.fov_x / 2)/100 * 360

        absolute_heading = heading_car_degrees + heading_camera_degrees + heading_sign_degrees
        return absolute_heading

    def csv_line(self,ocr,panorama):

        #fieldnames = ('sign_pk','text','latitude','longitude','languages','image_url','image_pk','sign_heading','sign_overlay','x1','x2','y1','y2')
        #header = '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' % fieldnames

        # if self.lat_sign is not None:
        #     txt = '%d\t%s\t%f\t%f\t%s\t%s\t%d\t%f\t%s\t%d\t%d\t%d\t%d\n' % \
        #            (self.pk,self.text,self.lat_sign,self.lon_sign,self.languages,AWS_BASE_URL + self.ocr.pano_image_name, self.ocr.pk, self.x_fraction()*360,MYSITE_URL+'viewer/overlaySigns/'+str(self.ocr.pk)+'/',self.x1,self.x2,self.y1,self.y2  ) 
        # else:
        #     txt = '%d\t%s\t%s\t%s\t%s\t%s\t%d\t%f\t%s\t%d\t%d\t%d\t%d\n' % \
        #            (self.pk,self.text,self.lat_sign,self.lon_sign,self.languages,AWS_BASE_URL + self.ocr.pano_image_name, self.ocr.pk, self.x_fraction()*360,MYSITE_URL+'viewer/overlaySigns/'+str(self.ocr.pk)+'/',self.x1,self.x2,self.y1,self.y2)

        txt = self.text +'\t'+\
              str(self.lat_sign) +'\t'+\
              str(self.lon_sign) +'\t'+\
              str(self.ocr.pk) +'\t'+\
              str(self.x_fraction()*360) +'\t'+\
              str(self.x1) +'\t'+\
              str(self.x2) +'\t'+\
              str(self.y1) +'\t'+\
              str(self.y2) +'\t'+\
              str(self.distance) +'\t'+\
              str(self.confidence) +'\t'+\
              str(panorama.year) +'\t'+\
              str(panorama.month) +'\t'+\
              str(panorama.lat) +'\t'+\
              str(panorama.lon) +'\t'+\
              str(panorama.num_links) +'\t'+\
              str(ocr.width_pano) +'\t'+\
              str(ocr.height_pano) +'\t'+\
              str(self.languages) + '\t'+\
              '\n'

        # remove problematic characters
        import re
        txt = re.sub('[\'\"]', '', txt)
        # return
        return txt

viewer/models.py
from django.db import models

# Create your models here.

ocr/views.py
from django.shortcuts import render
from django.http import HttpResponse
from panoramas.models import Panorama
import boto3
from mysite.settings import *
import ocr.nfov as nfov
from .models import *
from signs.models import Sign
import time
import random
import json
from django.core import serializers
import datetime

def worker_get_ocr(request, worker_id):
    # A clumsy way to solve concurrency conditions
    while(os.path.isfile('.lock')):
        print('database locked')
        time.sleep(random.uniform(0.1, 0.5))
    f = open(".lock","w")
    f.close()

    # # check if we are done with all ocr
    # # This is too slow to use. Maybe json text field too long?
    # count = len(Ocr.objects.filter(lock_ocr=False).values_list('pk',flat=True))
    # if count == 0:
    #    os.remove(".lock") 
    #    return HttpResponse("done")

    OVERRIDE = True
    SEND_LENGTH = 100
    if OVERRIDE is False:    
        try:
            pk_list = list(Ocr.objects.filter(lock_ocr=False)[0:SEND_LENGTH].values_list('pk',flat=True))
        except:
            # we are finished with queue!
            with open(BASE_DIR + "worker_log.txt", "a") as myfile:
                myfile.write('done with ocr to text\n')
            count = Ocr.objects.filter(lock_ocr=False).count()
            pk_list = list(Ocr.objects.filter(lock_ocr=False)[0:count].values_list('pk',flat=True))
        # update lock
        for pk in pk_list:
                o = Ocr.objects.get(pk=pk)
                o.lock_ocr = True
                o.save()
    else:
        ocr_list = QueueOcr.ocr_list(n=SEND_LENGTH)

    # serialize Ocr objects
    #o_list = Ocr.objects.filter(pk__in=pk_list).order_by('pk')
    o_list = ocr_list.order_by('pk')
    o_serialized = serializers.serialize("json", o_list)

    # serialize Panorama objects
    panorama_pk_list = o_list.values_list('panorama',flat=True)
    panorama_list = []
    for pk in panorama_pk_list:
        panorama_list.append(Panorama.objects.get(pk=pk))
    panorama_serialized = serializers.serialize("json", panorama_list)

    # debugging
    #print(pk_list)
    #print(panorama_pk_list)
    # log worker communication
    out_str = "sent ocr objects pk=[" + str(o_list.first().pk) + ' - ' + str(o_list.last().pk) + " to worker_id=" + str(worker_id) + " at " + str(datetime.datetime.now()) + "\n"
    with open(BASE_DIR + "worker_log.txt", "a") as myfile:
        myfile.write(out_str)

    # Remove lock against concurrency
    os.remove(".lock") 

    # combine Ocr, Panorama data
    data = {'ocr' : o_serialized,
            'panorama': panorama_serialized}
    return HttpResponse(json.dumps(data), content_type = "application/json")

# Create your views here.
def overview(request):
    count = len(Ocr.objects.all())
    return HttpResponse(count)

def overlay(request,ocr_pk,x1,x2,y1,y2):
    o = Ocr.objects.get(pk=ocr_pk)
    width = x2 - x1
    height = y2 - y1
    signs = [[ x1,y1,width,height,'' ]]
    context = {'ocr' : o,
               'signs' : signs,                                          
              }
    return render(request, 'ocr/detail.html',context)


def detail(request,ocr_pk):
    o = Ocr.objects.get(pk=ocr_pk)
    # parse json for signs
    from signs.controls import parse_json_to_sign
    texts,languages,boundingBoxes,confidences = parse_json_to_sign(o.json())
    signs = []
    for boundingBox,text in zip(boundingBoxes,texts):
        x1 = boundingBox[0]
        x2 = boundingBox[1]
        y1 = boundingBox[2]
        y2 = boundingBox[3]
        width = x2 - x1
        height = y2 - y1
        signs.append([x1,y1,width,height,text])
    context = {'ocr' : o,
               'signs' : signs,                                          
              }
    return render(request, 'ocr/detail.html',context)


# ocr/controls.py: worker_run_ocr uses this interface to communicate data back to master
# TODO: not secure
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def create_Ocr(request):
    post = request.POST
    json_str = post.get('json_str')
    d = ast.literal_eval(json_str)
    print(d)

    # create Ocr object and save
    o = Ocr(panorama = Panorama.objects.get(pk=d['panorama_pk']), 
            pano_image_name = d['pano_image_name'], 
            depth_image_name= d['depth_image_name'],
            width_depth =d['width_depth'],
            width_pano =d['width_pano'],
            height_depth =d['height_depth'],
            height_pano =d['height_pano'],
            direction= d['direction'],
            fov_x= d['fov_x'],
            fov_y= d['fov_y'],
            google_ocr_json = d['google_ocr_json']
            )
    o.save()

    # return to worker
    return HttpResponse('Ocr object created')

viewer/templates/viewer/ain.html
{% block javascript %}
{% endblock %}

{% block body_block %}

<h1>ain ={{ain}}</h1>


<h2>Links to ocr</h2>
{% for ocr_pk in ocr_pks %}
  <a href="{% url 'viewer:overlaySignsFOV' ocr_pk=ocr_pk fov=130 %}">{% url 'viewer:overlaySignsFOV' ocr_pk=ocr_pk fov=180 %}</a> <br />
{% endfor %}

<br />
<br />
<br />

<h2>Links to ocr with with option TEXT_DETECTION (low false positive, high false negative)</h2>
{% for ocr_pk in ocr_pks %}
  <a href="http://138.197.220.71:8886{% url 'viewer:overlaySignsFOV' ocr_pk=ocr_pk fov=180 %}">{% url 'viewer:overlaySignsFOV' ocr_pk=ocr_pk fov=180 %}</a> <br />
{% endfor %}
<br />
<br />
<br />



<h2>Instructions to adjust FOV (field of view)</h2>
Click on a link.<br /> 
Change last number in url to FOV (field of view) in degrees. Default 180. <br />
Example: If you want to change FOV from 180 to 70 degrees, change from: <br />
<a href="">http://127.0.0.1:8000/viewer/overlaySignsFOV/1587/180</a> into <br />
<a href="">http://127.0.0.1:8000/viewer/overlaySignsFOV/1587/70</a>

{% endblock %}

viewer/templates/viewer/mapPoint.html
{% block javascript %}
{% endblock %}

{% block body_block %}

<h1>MapPoint pk={{mapPoint.pk}}</h1>

{% for panorama in mapPoint.panorama_set.all %}
    {% include "viewer/template_panorama.html" with panorama=panorama %}

    <!--
    {% for ocr in panorama.ocr_set.all %}
        {% include "viewer/template_ocr.html" with ocr=ocr %}
    {% endfor %}
    -->

{% endfor %}

{% endblock %}

viewer/templates/viewer/ocr.html
{% block javascript %}
{% endblock %}

{% block body_block %}

<h1>ocr pk={{ocr.pk}}</h1>


<h2>Signs</h2>
{% for sign in ocr.sign_set.all %}
  <a href="{% url 'signs:detail' sign.pk %}">{{ sign.text }}</a> <br />
{% endfor %}


<h2> Raw json </h2>
{{ ocr.google_ocr_json }}

{% endblock %}

viewer/templates/viewer/overlaySigns.html
{% block javascript %}
{% endblock %}

{% block body_block %}

<style type="text/css" media="screen">
    .image_container {
        position:relative;
        margin-bottom: 20px;
    }
    .green {
      float: left;
      position: absolute;
      background-color: green;
      opacity: 0.5;
      z-index: 1000;
      color: yellow;
      text-align: center;
      font-weight: bold;
      font-size: 15;
    }

    .green:hover {
        opacity:0
    }


    .gray {
        filter: grayscale(100%);
    }
</style>

<div class="image_container">
    {% for sign in signs %}
        <div style="left:{{ sign.x1 }}px;top:{{ sign.y1 }};width:{{ sign.width }}px;height:{{ sign.height }}px" class="green">
            {{ sign.text }} , ain={{ sign.ain}}
        </div>  
    {% endfor %}
    <img src="{{ocr.url_pano_image }}" class="gray"/> <br />

</div>

{% endblock %}

viewer/templates/viewer/panorama.html
{% load mathfilters %}

{% block javascript %}
{% endblock %}

{% block body_block %}
<style>
#overlay_container_{{ocr.pk}} {
    width: {{ ocr.width_pano|mul:1.1 }}px;
    height: {{ocr.height_pano|mul:1.1 }}px;
}
</style>
      

<h1>Panorama pk={{panorama.pk}}</h1>


{% for ocr in panorama.ocr_set.all %}

<a href="{% url 'viewer:ocr' ocr.pk %}">
<h2>ocr pk = {{ocr.pk}}</h2>
</a>
<div id="overlay_container_{{ocr.pk}}">
<iframe src="{% url 'viewer:overlaySigns' ocr.pk %}" width="{{ ocr.width_pano|mul:1.1 }}" height="{{ ocr.height_pano|mul:1.1 }}" 
        style="-webkit-transform:scale(1);-moz-transform-scale(1)
               -moz-transform-origin: top left; -webkit-transform-origin: top left; -o-transform-origin: top left; -ms-transform-origin: top left; transform-origin: top left;">
</iframe>
</div>


{% endfor %}

{% endblock %}

viewer/templates/viewer/template_ocr.html
{% load mathfilters %}

<h3>
  <a href="{% url 'viewer:ocr' ocr.pk %}">
    ocr pk = {{ ocr.pk }}
  </a>    
</h3>

<style>
  #overlay_container_{{ocr.pk}} {
    width: {{ ocr.width_pano|mul:1.1 }}px;
    height: {{ocr.height_pano|mul:1.1 }}px;
  }
</style>

<div id="overlay_container_{{ocr.pk}}">
<iframe src="{% url 'viewer:overlaySigns' ocr.pk %}" width="{{ ocr.width_pano|mul:1.1 }}" height="{{ ocr.height_pano|mul:1.1 }}" 
        style="-webkit-transform:scale(1);-moz-transform-scale(1)
               -moz-transform-origin: top left; -webkit-transform-origin: top left; -o-transform-origin: top left; -ms-transform-origin: top left; transform-origin: top left;">
</iframe>
</div>

viewer/templates/viewer/template_panorama.html
<h2>
  <a href="{% url 'viewer:panorama' panorama.pk %}">Panorama pk = {{ panorama.pk }}</a>
</h2>

<a href="{{ panorama.url_pano_image }}">panorama image</a> <br />
<a href="{{ panorama.url_depth_image }}">depth image</a> <br />

date google car = {{ panorama.month }}-{{ panorama.year }} <br />
heading = {{ panorama.heading }} <br />
(lon,lat) = ( {{ panorama.lon }},{{panorama.lat}}) <br />
panorama id = {{ panorama.panoid }} <br />
address = {{ panorama.address }} <br />
num_links = {{ panorama.num_links }} <br />
MapPoint pk = {{ panorama.mapPoint.pk }} <br />
<iframe src="{% url 'panoramas:googleViewer' panorama.pk %}" width="620" height="320">
</iframe>